load("//multiformats:multiformats.bzl", "COPTS")

cc_library(
    name = "varint",
    srcs = [
        "varint.cc",
        "varint.h",
    ],
    hdrs = glob(["*.h"]),
    copts = COPTS,
    visibility = ["//visibility:public"],
)
