load("//multiformats:multiformats.bzl", "COPTS")

cc_library(
    name = "util",
    srcs = glob([
        "*.h",
        "*.cc",
    ]),
    hdrs = glob(["*.h"]),
    copts = COPTS,
    visibility = ["//visibility:public"],
)
